---
- hosts: 192.168.0.45
  gather_facts: yes
  vars:
    ansible_connection: winrm
    ansible_winrm_user: administrador
    ansible_winrm_password: "12345678"
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore

  tasks:

    - include_role:
        name: hyperv_provisioning