- name: Logando no openshift via ansible
  community.okd.openshift_auth:
    host: https://api.ocppr.orizon.local:6443
    username: "{{useropenshift}}"
    password: "{{passopenshift}}"
    validate_certs: false
  register: openshift_auth_results

- name: Logando no openshift via shell
  ansible.builtin.shell: |
    oc login --token={{openshift_auth_results.openshift_auth.api_key}} \
    --server=https://api.ocppr.orizon.local:6443 --insecure-skip-tls-verify=false || /bin/true

- set_fact:
    sync: "{{ lookup('community.general.random_string', upper=false, lower=false, special=false) }}"

- name: Realizando o sync com AD orizon.local
  ansible.builtin.shell: |
    oc create job sync-ldap-{{namespaceocp}}-{{sync}} -n ldap-sync-job --from=cronjob/cronjob-ldap-group-sync

- name: Fazendo logout do openshift via ansible
  community.okd.openshift_auth:
    host: https://api.ocppr.orizon.local:6443
    api_key: "{{openshift_auth_results.openshift_auth.api_key}}"
    validate_certs: false
    state: absent
  when: openshift_auth_results.openshift_auth.api_key is defined
  ignore_errors: true

- name: Fazendo logout do openshift via shell
  ansible.builtin.shell: oc logout || /bin/true