- name: Criar diretório C:\meu_diretorio
  ansible.windows.win_file:
    path: G:\vms\{{vmname}}
    state: directory

- name: Obtain information about a file
  ansible.windows.win_stat:
    path: G:\vms\{{vmname}}\{{vmname}}.vhdx
  register: file_info

- debug:
    var: file_info.stat.exists

- name: Clonando o template
  ansible.windows.win_powershell:
    script: |
      New-VHD -ParentPath "G:\vms\template_linux\Virtual Hard Disks\template_linux.vhdx" `
      -Path G:\vms\{{vmname}}\{{vmname}}.vhdx -Differencing
  changed_when: file_info.stat.exists == False

- name: verificando se a vm existe
  ansible.windows.win_powershell:
    script: |
      Get-VM -Name {{vmname}} -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Name
  register: vm_exist

- name: criando a vm
  ansible.windows.win_powershell:
    script: |
      New-VM -Name "{{vmname}}" -MemoryStartupBytes 4GB -BootDevice VHD -VHDPath G:\vms\{{vmname}}\{{vmname}}.vhdx `
      -Generation 2 -SwitchName "rede_home"
  when: vm_exist.output not exists and template_exist.output == true

- name: Configurando vm 
  ansible.windows.win_powershell:
    script: "{{item}}"
  loop:
    - Set-VMProcessor -VMName {{vmname}} -Count 4
    - Set-VMFirmware -VMName {{vmname}} -EnableSecureBoot Off
    - Set-VM -Name {{vmname}} -CheckpointType Standard
    - Set-VM -Name {{vmname}} -AutomaticCheckpointsEnabled $false
    - Set-VM -Name {{vmname}} -AutomaticStartAction Nothing
    - Set-VM -Name {{vmname}} -AutomaticStopAction Shutdown
  when: vm_exist.output is not defined and template_exist.output == True