- name: Criando o diretório da VM
  ansible.windows.win_file:
    path: G:\vms\{{vmname}}
    state: directory

- name: Verificando se o template VHDX existe
  ansible.windows.win_stat:
    path: G:\vms\{{vmname}}\{{vmname}}.vhdx
  register: file_info

- name: Clonando o template VHDX
  ansible.windows.win_powershell:
    script: |
      New-VHD -ParentPath "G:\vms\template_linux\Virtual Hard Disks\template_linux.vhdx" `
      -Path G:\vms\{{vmname}}\{{vmname}}.vhdx -Differencing
  when: file_info.stat.exists == false

- name: Verificando se a vm existe
  ansible.windows.win_powershell:
    script: |
      Get-VM -Name {{vmname}} -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Name
  register: vm_exist

- name: Provisionando a VM
  ansible.windows.win_powershell:
    script: |
      New-VM -Name "{{vmname}}" -MemoryStartupBytes 4GB -BootDevice VHD -VHDPath G:\vms\{{vmname}}\{{vmname}}.vhdx `
      -Generation 2 -SwitchName "rede_home"
  when: vm_exist.output | length == 0

- name: Configurando a VM 
  ansible.windows.win_powershell:
    script: "{{item}}"
  loop:
    - Set-VMProcessor -VMName {{vmname}} -Count 4
    - Set-VMFirmware -VMName {{vmname}} -EnableSecureBoot Off
    - Set-VM -Name {{vmname}} -CheckpointType Standard
    - Set-VM -Name {{vmname}} -AutomaticCheckpointsEnabled $false
    - Set-VM -Name {{vmname}} -AutomaticStartAction Nothing
    - Set-VM -Name {{vmname}} -AutomaticStopAction Shutdown
    - Start-VM -Name {{vmname}}